# Site settings
title: Dream Catcher
header-img: img/home-bg.jpg
email: rony.islam1295@gmail.com
description: "A Collection of Thoughts, Rants, and Punctuation."
baseurl: ""
url: "https://dreamcatcher95.github.io"
twitter_username: 
github_username:  
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
